#!/bin/bash

#This condition will verify if youtube-dl is installed
if test -f /usr/local/bin/youtube-dl; then
	echo -e "youtube-dl is installed"
else

#!/bin/bash
# Para referencia:
# https://ytdl-org.github.io/youtube-dl/download.html

#instalar dependencias aqui
clear
echo "INSTALANDO DEPENDENCIAS SE FOR NECESSARIO"
echo -e "-----------------------------------------\n"
sudo apt-get update -y && sudo apt-get install python3-venv python3-pip && sudo -H pip3 install --upgrade youtube-dl && sudo apt-get install ffmpeg -y

echo -e "\nEXECUTANDO O DOWNLOAD DO VIDEO E TRANSFORMANDO EM MP3"
echo -e "-----------------------------------------------------\n"
sudo youtube-dl --yes-playlist --extract-audio --audio-format mp3 $1

exit 1
fi

#This condition will verify if there is a youtube link to download.
if test -z "$1"
then
      echo "You need to add the youtube link"
else
      echo "Read to install"
      cd /home/$USER &&  clear && sudo youtube-dl --yes-playlist --extract-audio --audio-format mp3 $1
fi

exit 1
